"""add_image_url_to_products

Revision ID: 9767e0bc90d2
Revises: 5f72f77e0ad0
Create Date: 2026-09-10 00:12:59.363969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9767e0bc90d2"
down_revision: Union[str, Sequence[str], None] = "5f72f77e0ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_url")
    # ### end Alembic commands ###
