"""make_sender_number_optional_in_topups_and_payments

Revision ID: c5e8c1f86067
Revises: cd20c9669aaa
Create Date: 2026-10-04 15:13:48.134292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e8c1f86067'
down_revision: Union[str, Sequence[str], None] = 'cd20c9669aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'sender_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('topups', 'sender_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topups', 'sender_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'sender_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
