"""create incoming_sms table

Revision ID: dd05229b6bb2
Revises: 8095317f1c9b
Create Date: 2026-09-11 02:32:30.773523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd05229b6bb2"
down_revision: Union[str, Sequence[str], None] = "8095317f1c9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incoming_sms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("raw_message", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("sender_phone", sa.String(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("sim_slot", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("is_matched", sa.Boolean(), nullable=False),
        sa.Column("matched_entity_type", sa.String(), nullable=True),
        sa.Column("matched_entity_id", sa.Integer(), nullable=True),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incoming_sms_id"), "incoming_sms", ["id"], unique=False)
    op.create_index(
        op.f("ix_incoming_sms_is_deleted"), "incoming_sms", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_incoming_sms_is_matched"), "incoming_sms", ["is_matched"], unique=False
    )
    op.create_index(
        op.f("ix_incoming_sms_provider"), "incoming_sms", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_incoming_sms_sender"), "incoming_sms", ["sender"], unique=False
    )
    op.create_index(
        op.f("ix_incoming_sms_sender_phone"),
        "incoming_sms",
        ["sender_phone"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incoming_sms_status"), "incoming_sms", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_incoming_sms_transaction_id"),
        "incoming_sms",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incoming_sms_transaction_id"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_status"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_sender_phone"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_sender"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_provider"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_is_matched"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_is_deleted"), table_name="incoming_sms")
    op.drop_index(op.f("ix_incoming_sms_id"), table_name="incoming_sms")
    op.drop_table("incoming_sms")
    # ### end Alembic commands ###
